version: '3.9'

services:
  redis:
    image: redis
    container_name: redis
    ports:
      - '6379:6379'

  postgres:
    image: postgres
    restart: always
    container_name: postgres
    env_file:
      - .env.docker
    environment:
#      POSTGRES_USER: ${POSTGRES_USER}
#      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/pgdata
    volumes:
      - .:/code
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: app
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - '8000:8000'
    depends_on:
      - postgres
    env_file:
      - .env.docker
    volumes:
      - .:/code

  celery_worker:
    build: .
    container_name: celery_worker
    tty: true
    command: celery -A config worker -l INFO -P eventlet
    env_file:
      - .env.docker
    depends_on:
      - redis
      - app

  celery_beat:
    build: .
    container_name: celery_beat
    tty: true
    command: celery -A config beat -l INFO
    env_file:
      - .env.docker
    depends_on:
      - redis
      - app

volumes:
  pgdata: