# Generated by Django 5.0.3 on 2024-03-29 12:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0005_habit_is_pleasant_alter_habit_linked_habit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Habit',
            new_name='Habits',
        ),
    ]
