# Generated by Django 5.0.3 on 2024-03-29 12:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0006_rename_habit_habits'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Habits',
            new_name='Habit',
        ),
    ]
