# Generated by Django 5.0.3 on 2024-03-29 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0008_place_alter_habit_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название интервала')),
                ('days', models.IntegerField(default=0, verbose_name='интервал в днях')),
                ('hours', models.IntegerField(default=0, verbose_name='интервал в часах')),
                ('minutes', models.IntegerField(verbose_name='интервал в минутах')),
            ],
            options={
                'verbose_name': 'Интервал',
                'verbose_name_plural': 'Интервалы',
            },
        ),
        migrations.RemoveField(
            model_name='habit',
            name='regularity',
        ),
        migrations.AlterField(
            model_name='habit',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='habits.place', verbose_name='место применения'),
        ),
        migrations.AddField(
            model_name='habit',
            name='interval',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='habits.interval', verbose_name='периодичность'),
        ),
    ]
