# Generated by Django 5.0.3 on 2024-03-29 13:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0009_interval_remove_habit_regularity_alter_habit_place_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='started_on',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='начало действия'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='habit',
            name='started_time',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='время действия'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='habit',
            name='execution_time',
            field=models.IntegerField(default=120, verbose_name='время на выполнение в секундах'),
        ),
    ]
