# Generated by Django 5.0.3 on 2024-03-29 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0011_remove_habit_started_time_alter_habit_started_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habit',
            old_name='user',
            new_name='created_by',
        ),
    ]
